export const TEMPLATES = {
  report: [
    { type: 'heading', text: 'Q4 2025 Performance Report', level: 1 },
    { type: 'paragraph', text: 'This report summarizes the **key performance indicators** across all business units for the *fourth quarter* of fiscal year 2025. Overall revenue grew by **23% year-over-year**, driven primarily by expansion in the __Asia Pacific__ region and strong adoption of our *enterprise product tier*.' },
    { type: 'spacer', height: 10 },
    { type: 'heading', text: 'Revenue by Region', level: 2 },
    { type: 'table', headers: 'Region, Q3 Revenue, Q4 Revenue, Growth, Notes', rows: 'North America (United States and Canada), $12.4M, $14.1M, +13.7%, Strong enterprise adoption driven by new product launches\nEurope & United Kingdom, $8.7M, $10.2M, +17.2%, GDPR compliance improvements boosted customer confidence significantly\nAsia Pacific (Japan and Southeast Asia), $5.1M, $7.8M, +52.9%, Fastest growing region with major wins in financial services sector\nLatin America, $2.3M, $2.9M, +26.1%, New partnerships with local distributors in Brazil and Mexico\nMiddle East & Africa, $1.1M, $1.5M, +36.4%, Early stage but promising pipeline in UAE and South Africa' },
    { type: 'spacer', height: 10 },
    { type: 'heading', text: 'Key Highlights', level: 2 },
    { type: 'paragraph', text: 'Enterprise tier adoption increased by 45% quarter-over-quarter, with 127 new enterprise accounts onboarded. Customer retention rate remained strong at 94.2%, up from 91.8% in Q3. The average deal size grew from $48K to $62K, reflecting successful upsell initiatives.\n\nProduct development velocity improved with 3 major feature releases shipped on schedule. Infrastructure costs were reduced by 18% through optimization efforts, improving gross margins from 71% to 74%.' },
    { type: 'divider' },
    { type: 'stat-row', items: 'Total Revenue: $36.5M, Growth: +23% YoY, Customers: 2847, NPS: 72' },
    { type: 'spacer', height: 10 },
    { type: 'heading', text: 'Outlook for Q1 2026', level: 2 },
    { type: 'paragraph', text: 'Based on current pipeline analysis and contracted revenue, we project Q1 2026 revenue between $38M and $41M.' },
    { type: 'heading', text: 'Key Initiatives', level: 3 },
    { type: 'bullet-list', items: 'Launch of AI-powered analytics module with predictive insights\nExpansion into Southeast Asian market starting with Singapore and Indonesia\nRollout of partner certification program with 50 target partners\nMigration of legacy customers to the new enterprise tier' },
    { type: 'quote', text: 'This quarter represents a turning point for the company. We are transitioning from regional growth to a truly global presence, with infrastructure and partnerships to support scale.', attribution: 'CEO, Annual Planning Meeting' },
    { type: 'heading', text: 'Risk Factors', level: 3 },
    { type: 'numbered-list', items: 'Potential regulatory changes in the EU data privacy landscape may require compliance updates\nCurrency headwinds in emerging markets could impact reported revenue by 2-3%\nCompetitor product launch expected in Q2 may affect win rates in mid-market segment\nKey engineering hires still needed for the AI module delivery timeline' },
    { type: 'spacer', height: 10 },
    { type: 'two-column', left: 'Contact: investor-relations@company.com\nPrepared by: Finance Team\nClassification: Internal — Confidential', right: 'Next review: Q1 2026 Board Meeting\nDistribution: Executive Team, Board of Directors\nVersion: 2.1 Final' },
  ],
  invoice: [
    { type: 'heading', text: 'INVOICE', level: 1 },
    { type: 'stat-row', items: 'Invoice #: INV-2025-0847, Date: March 31 2025, Due: April 30 2025, Status: Pending' },
    { type: 'spacer', height: 6 },
    { type: 'divider' },
    { type: 'spacer', height: 6 },
    { type: 'heading', text: 'Bill To', level: 2 },
    { type: 'key-value', items: 'Company: Acme Corporation\nAddress: 123 Innovation Drive, Suite 400, San Francisco, CA 94105\nEmail: accounts@acme.corp\nTax ID: US-84-2847291' },
    { type: 'spacer', height: 10 },
    { type: 'heading', text: 'Items', level: 2 },
    { type: 'table', headers: 'Description, Qty, Unit Price, Total', rows: 'Enterprise License (Annual) — Full platform access including API and analytics dashboard, 1, $24000.00, $24000.00\nPremium Support Plan with 24/7 coverage and dedicated account manager, 1, $4800.00, $4800.00\nCustom Integration Setup — REST API connector for Salesforce and HubSpot, 12 hrs, $200.00, $2400.00\nData Migration Service including historical data import and validation, 1, $1500.00, $1500.00' },
    { type: 'spacer', height: 10 },
    { type: 'stat-row', items: 'Subtotal: $32700.00, Tax (8.5%): $2779.50, Total Due: $35479.50' },
    { type: 'divider' },
    { type: 'spacer', height: 6 },
    { type: 'quote', text: 'Payment terms: Net 30. Please remit payment via wire transfer to the account details provided separately. A 1.5% monthly late fee applies to overdue balances.', attribution: '' },
    { type: 'paragraph', text: 'For questions regarding this invoice, contact [billing@tangentflow.com](mailto:billing@tangentflow.com) or visit [tangentflow.com](https://tangentflow.com).' },
  ],
  catalog: [
    { type: 'heading', text: 'Product Catalog — Spring 2026', level: 1 },
    { type: 'paragraph', text: 'Complete listing of available products with specifications and pricing. All items subject to availability. Volume discounts available for orders exceeding 100 units.' },
    { type: 'spacer', height: 8 },
    { type: 'heading', text: 'Electronics & Components', level: 2 },
    { type: 'table', headers: 'SKU, Product Name, Description, Stock, Price', rows: 'EL-4820, Arduino Mega 2560 Rev3, Microcontroller board based on the ATmega2560 with 54 digital I/O pins and 16 analog inputs. Ideal for complex robotics and automation projects., 342, $38.50\nEL-4821, Raspberry Pi 5 (8GB), Single-board computer featuring a 2.4GHz quad-core Arm Cortex-A76 CPU with 8GB LPDDR4X RAM. Supports dual 4K displays and PCIe 2.0., 89, $80.00\nEL-4822, ESP32-S3 DevKit, Wi-Fi and Bluetooth LE development board with dual-core 240MHz processor and 512KB SRAM. Built-in USB-OTG and support for AI acceleration., 1205, $12.99\nEL-4823, OLED Display Module 1.3 inch SH1106, 128x64 pixel monochrome OLED display with I2C/SPI interface. Ultra-low power consumption suitable for battery-powered IoT devices., 567, $7.25\nEL-4824, LiPo Battery 3.7V 2000mAh, Rechargeable lithium polymer battery with built-in protection circuit. Dimensions: 50x34x10mm. Suitable for portable electronics and wearable devices., 2340, $4.50\nEL-4825, USB-C PD Charger 65W GaN, Gallium nitride fast charger supporting USB Power Delivery 3.0 and Quick Charge 4+. Triple port design with intelligent power distribution., 178, $29.99' },
    { type: 'spacer', height: 10 },
    { type: 'heading', text: 'Sensors & Modules', level: 2 },
    { type: 'table', headers: 'SKU, Product Name, Description, Stock, Price', rows: 'SN-1001, BME280 Environmental Sensor, Combined temperature/humidity/barometric pressure sensor with I2C and SPI interfaces. Accuracy: ±1°C temp and ±3% humidity. Operating range: -40 to 85°C., 890, $3.99\nSN-1002, VL53L1X Time-of-Flight Sensor, Laser-based distance measurement sensor with range up to 4 meters. Programmable ROI and multiple measurement modes for advanced gesture recognition., 445, $11.50\nSN-1003, MAX30102 Pulse Oximeter & Heart Rate Monitor, Integrated pulse oximetry and heart-rate sensor module with red and infrared LEDs and photodetector. Medical-grade accuracy for wearable health devices., 623, $8.75\nSN-1004, MPU-6050 6-Axis IMU Accelerometer + Gyroscope, MEMS-based motion tracking device with 16-bit ADC for each channel. DMP for complex motion processing. I2C interface with programmable interrupt., 1560, $2.99' },
    { type: 'divider' },
    { type: 'paragraph', text: 'Prices shown are per-unit retail. Contact sales@catalog.example.com for wholesale pricing. All specifications subject to change without notice.' },
  ],
  resume: [
    { type: 'heading', text: 'Alex Morgan', level: 1 },
    { type: 'paragraph', text: 'Senior Software Engineer with 8+ years of experience building scalable web applications and distributed systems. Passionate about developer tools, performance optimization, and open-source software.' },
    { type: 'key-value', items: 'Email: alex.morgan@email.com\nLocation: San Francisco, CA\nWebsite: alexmorgan.dev\nGitHub: github.com/alexmorgan' },
    { type: 'divider' },
    { type: 'heading', text: 'Experience', level: 2 },
    { type: 'heading', text: 'Senior Engineer — Stripe', level: 3 },
    { type: 'paragraph', text: 'Jan 2022 — Present' },
    { type: 'bullet-list', items: 'Led the redesign of the payment processing pipeline, reducing latency by 40%\nBuilt and maintained internal tooling used by 200+ engineers across 12 teams\nMentored 4 junior engineers through structured onboarding and pair programming\nContributed to open-source SDK libraries with 15K+ GitHub stars' },
    { type: 'spacer', height: 6 },
    { type: 'heading', text: 'Software Engineer — Vercel', level: 3 },
    { type: 'paragraph', text: 'Mar 2019 — Dec 2021' },
    { type: 'bullet-list', items: 'Developed core deployment infrastructure handling 2M+ deployments per month\nImplemented edge function runtime with sub-50ms cold start times\nDesigned and shipped the team dashboard used by 100K+ developers\nReduced build times by 60% through incremental compilation and caching strategies' },
    { type: 'spacer', height: 6 },
    { type: 'heading', text: 'Junior Developer — Notion', level: 3 },
    { type: 'paragraph', text: 'Jun 2017 — Feb 2019' },
    { type: 'bullet-list', items: 'Built real-time collaboration features using CRDTs and WebSocket connections\nOptimized database queries reducing page load times from 3s to 400ms\nShipped the first version of the API integration framework' },
    { type: 'divider' },
    { type: 'heading', text: 'Skills', level: 2 },
    { type: 'two-column', left: 'Languages: TypeScript, Go, Rust, Python\nFrameworks: React, Next.js, Node.js\nDatabases: PostgreSQL, Redis, DynamoDB', right: 'Infrastructure: AWS, Kubernetes, Terraform\nTools: Git, Docker, CI/CD, Datadog\nOther: System design, technical writing' },
    { type: 'divider' },
    { type: 'heading', text: 'Education', level: 2 },
    { type: 'key-value', items: 'Degree: B.S. Computer Science\nUniversity: UC Berkeley\nGraduated: 2017\nHonors: Dean\'s List, ACM Programming Contest Finalist' },
  ],
  proposal: [
    { type: 'heading', text: 'Project Proposal', level: 1 },
    { type: 'paragraph', text: 'Mobile App Redesign for GreenLeaf Health' },
    { type: 'spacer', height: 6 },
    { type: 'key-value', items: 'Prepared by: TangentFlow Design Studio\nPrepared for: GreenLeaf Health Inc.\nDate: March 31 2026\nValid until: April 30 2026\nProject ID: PRJ-2026-041' },
    { type: 'divider' },
    { type: 'heading', text: 'Executive Summary', level: 2 },
    { type: 'paragraph', text: 'This proposal outlines a comprehensive redesign of the GreenLeaf Health mobile application. The current app suffers from low user engagement (12% DAU/MAU ratio) and poor onboarding completion (34%). Our approach combines user research, modern UI patterns, and performance optimization to deliver a significantly improved patient experience.' },
    { type: 'heading', text: 'Objectives', level: 2 },
    { type: 'numbered-list', items: 'Increase daily active users by 40% within 6 months of launch\nImprove onboarding completion rate from 34% to 75%\nReduce average task completion time by 50%\nAchieve App Store rating of 4.5+ (currently 3.2)\nEnsure WCAG 2.1 AA accessibility compliance across all screens' },
    { type: 'heading', text: 'Scope of Work', level: 2 },
    { type: 'table', headers: 'Phase, Deliverables, Timeline, Cost', rows: 'Discovery & Research, User interviews (20 participants) and competitive analysis and current app audit, Weeks 1-3, $18000\nUX Design, Information architecture and wireframes and user flow diagrams and usability testing, Weeks 4-7, $24000\nUI Design, High-fidelity mockups and design system and interactive prototype and developer handoff, Weeks 8-11, $28000\nDevelopment Support, Design QA and asset delivery and implementation reviews, Weeks 12-18, $15000' },
    { type: 'spacer', height: 6 },
    { type: 'stat-row', items: 'Total Investment: $85000, Timeline: 18 weeks, Team Size: 4 people' },
    { type: 'heading', text: 'Why Us', level: 2 },
    { type: 'bullet-list', items: '12 years of experience in healthcare app design with HIPAA compliance expertise\nPortfolio includes 3 apps with 1M+ downloads in the health and wellness category\nDedicated accessibility specialist on every project\nAgile methodology with bi-weekly demos and continuous stakeholder feedback' },
    { type: 'divider' },
    { type: 'heading', text: 'Terms & Conditions', level: 2 },
    { type: 'quote', text: 'Payment schedule: 30% upon signing, 30% at design completion, 40% at project delivery. All deliverables remain property of GreenLeaf Health upon final payment. This proposal is valid for 30 days from the date above.', attribution: '' },
    { type: 'two-column', left: 'Client Signature:\n\n\n______________________________\nDate:', right: 'Provider Signature:\n\n\n______________________________\nDate:' },
  ],
  meeting: [
    { type: 'heading', text: 'Meeting Notes', level: 1 },
    { type: 'key-value', items: 'Meeting: Sprint 24 Planning\nDate: March 31 2026\nTime: 10:00 AM — 11:30 AM PST\nLocation: Conference Room B / Zoom\nFacilitator: Jordan Kim' },
    { type: 'spacer', height: 4 },
    { type: 'heading', text: 'Attendees', level: 2 },
    { type: 'two-column', left: 'Jordan Kim (Engineering Lead)\nPriya Sharma (Product Manager)\nTom Chen (Backend Engineer)', right: 'Lisa Park (Frontend Engineer)\nMarco Rossi (Designer)\nAna Silva (QA Lead)' },
    { type: 'divider' },
    { type: 'heading', text: 'Agenda', level: 2 },
    { type: 'numbered-list', items: 'Sprint 23 retrospective and velocity review\nSprint 24 backlog grooming and story point estimation\nBlocked items and dependency resolution\nRelease planning for v2.4\nOpen discussion' },
    { type: 'heading', text: 'Key Decisions', level: 2 },
    { type: 'bullet-list', items: 'Agreed to postpone the dashboard redesign to Sprint 25 due to API dependency on the analytics team\nApproved the new error handling approach proposed by Tom — will use structured error types instead of string codes\nDecided to split the user settings epic into 3 smaller stories for better parallelization\nMarco will deliver the updated design system tokens by Wednesday to unblock Lisa\'s work on the component library' },
    { type: 'heading', text: 'Action Items', level: 2 },
    { type: 'table', headers: 'Action, Owner, Due Date, Status', rows: 'Write RFC for new error handling approach, Tom Chen, Apr 3, In Progress\nUpdate design system tokens in Figma, Marco Rossi, Apr 2, Not Started\nSchedule dependency sync with Analytics team, Priya Sharma, Apr 1, Not Started\nSet up E2E test suite for payment flow, Ana Silva, Apr 4, Not Started\nReview and estimate backlog items for Sprint 25, Jordan Kim, Apr 7, Not Started' },
    { type: 'spacer', height: 8 },
    { type: 'heading', text: 'Parking Lot', level: 2 },
    { type: 'quote', text: 'Priya raised the question of migrating from REST to GraphQL for the mobile API. The team agreed this needs a separate deep-dive session. Jordan will schedule a 1-hour technical discussion for next week.', attribution: '' },
    { type: 'divider' },
    { type: 'paragraph', text: 'Next meeting: April 14 2026, 10:00 AM PST. Priya to send updated agenda by April 11.' },
  ],
  receipt: [
    { type: 'heading', text: 'RECEIPT', level: 1 },
    { type: 'stat-row', items: 'Receipt #: RCP-8294, Date: March 31 2026, Payment: Credit Card, Status: Paid' },
    { type: 'divider' },
    { type: 'heading', text: 'From', level: 2 },
    { type: 'key-value', items: 'Business: TangentFlow Inc.\nAddress: 548 Market St, Suite 300, San Francisco, CA 94104\nEmail: billing@tangentflow.com\nTax ID: US-82-1938475' },
    { type: 'spacer', height: 6 },
    { type: 'heading', text: 'To', level: 2 },
    { type: 'key-value', items: 'Customer: Sarah Johnson\nEmail: sarah.johnson@company.com\nAccount: ACC-29481' },
    { type: 'spacer', height: 6 },
    { type: 'heading', text: 'Items', level: 2 },
    { type: 'table', headers: 'Description, Qty, Price, Amount', rows: 'TangentFlow Pro — Annual subscription, 1, $228.00, $228.00\nAdditional team seats (3 seats), 3, $60.00, $180.00\nCustom font pack add-on, 1, $29.00, $29.00' },
    { type: 'spacer', height: 4 },
    { type: 'stat-row', items: 'Subtotal: $437.00, Tax (8.5%): $37.15, Total Paid: $474.15' },
    { type: 'divider' },
    { type: 'two-column', left: 'Payment method: Visa ending in 4829\nTransaction ID: txn_3K8mPQ2eZv\nProcessed: March 31 2026 at 2:14 PM PST', right: 'Billing period: Apr 1 2026 — Mar 31 2027\nAuto-renewal: Enabled\nNext billing date: March 31 2027' },
    { type: 'spacer', height: 10 },
    { type: 'quote', text: 'This receipt confirms payment has been processed successfully. No further action is required. For refund requests, please contact support within 14 days of purchase.', attribution: '' },
  ],
  nda: [
    { type: 'heading', text: 'Non-Disclosure Agreement', level: 1 },
    { type: 'paragraph', text: 'This Non-Disclosure Agreement ("Agreement") is entered into as of March 31, 2026 ("Effective Date") by and between the following parties.' },
    { type: 'two-column', left: 'Disclosing Party:\nTangentFlow Inc.\n548 Market St, Suite 300\nSan Francisco, CA 94104', right: 'Receiving Party:\n[Company Name]\n[Address]\n[City, State, ZIP]' },
    { type: 'divider' },
    { type: 'heading', text: '1. Definition of Confidential Information', level: 2 },
    { type: 'paragraph', text: '"Confidential Information" means any and all non-public information, whether in oral, written, electronic, or visual form, disclosed by the Disclosing Party to the Receiving Party, including but not limited to:' },
    { type: 'bullet-list', items: 'Trade secrets, inventions, patents, copyrights, and other intellectual property\nBusiness plans, strategies, financial data, and projections\nCustomer lists, vendor relationships, and pricing information\nSoftware source code, algorithms, architectures, and technical specifications\nProduct roadmaps, unreleased features, and development timelines\nEmployee information, compensation data, and organizational structure' },
    { type: 'heading', text: '2. Obligations of the Receiving Party', level: 2 },
    { type: 'paragraph', text: 'The Receiving Party agrees to:' },
    { type: 'numbered-list', items: 'Hold all Confidential Information in strict confidence and protect it using the same degree of care it uses to protect its own confidential information, but in no event less than reasonable care\nNot disclose any Confidential Information to any third party without the prior written consent of the Disclosing Party\nUse the Confidential Information solely for the purpose of evaluating or pursuing a business relationship between the parties\nLimit access to Confidential Information to those employees, agents, or advisors who have a need to know and who are bound by confidentiality obligations no less restrictive than those contained herein\nImmediately notify the Disclosing Party of any unauthorized use or disclosure of Confidential Information' },
    { type: 'heading', text: '3. Term and Termination', level: 2 },
    { type: 'paragraph', text: 'This Agreement shall remain in effect for a period of two (2) years from the Effective Date. The obligations of confidentiality shall survive the termination or expiration of this Agreement for a period of three (3) years following such termination or expiration.' },
    { type: 'heading', text: '4. Return of Materials', level: 2 },
    { type: 'paragraph', text: 'Upon termination of this Agreement or upon written request by the Disclosing Party, the Receiving Party shall promptly return or destroy all Confidential Information in its possession, including all copies, notes, summaries, and derivatives thereof, and shall certify in writing that it has done so.' },
    { type: 'heading', text: '5. Governing Law', level: 2 },
    { type: 'paragraph', text: 'This Agreement shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of laws principles. Any disputes arising under this Agreement shall be subject to the exclusive jurisdiction of the state and federal courts located in San Francisco County, California.' },
    { type: 'divider' },
    { type: 'heading', text: 'Signatures', level: 2 },
    { type: 'two-column', left: 'Disclosing Party:\n\n\n______________________________\nName:\nTitle:\nDate:', right: 'Receiving Party:\n\n\n______________________________\nName:\nTitle:\nDate:' },
  ],
  multilang: [
    { type: 'heading', text: 'Multilingual Document Demo', level: 1 },
    { type: 'paragraph', text: 'This document demonstrates how Pretext handles text wrapping across different languages and scripts. Each paragraph below contains real text that wraps correctly regardless of script complexity.' },
    { type: 'spacer', height: 8 },
    { type: 'heading', text: 'English', level: 2 },
    { type: 'paragraph', text: 'The quick brown fox jumps over the lazy dog. This classic pangram contains every letter of the English alphabet and serves as a standard test for font rendering and text layout systems across different platforms.' },
    { type: 'heading', text: 'Emoji Mixed Content', level: 2 },
    { type: 'paragraph', text: 'Performance metrics look great! Revenue is up 23% and customer satisfaction scored 4.8/5.0 this quarter. The team shipped 12 features across 3 product lines. Next quarter targets: $15M ARR and 500 new enterprise accounts.' },
    { type: 'heading', text: 'Technical Content', level: 2 },
    { type: 'paragraph', text: 'The API endpoint /v2/users/{id}/preferences accepts PATCH requests with a JSON body containing key-value pairs. Rate limiting is enforced at 1000 req/min per API key. Response times average 45ms at p50 and 120ms at p99. Authentication uses OAuth 2.0 with PKCE flow for public clients.' },
    { type: 'divider' },
    { type: 'paragraph', text: 'All text above was measured and wrapped using Pretext — pure JavaScript text layout with no DOM dependency. The PDF was generated with pdf-lib using the coordinates calculated by Pretext.' },
  ],
}
